SimpleToDolist/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleToDoList.Application.Contracts;
using System;

namespace SimpleToDoList.Pages
{
    public class EditModel : PageModel
    {
        public Guid Id { get; set; }
        public string EditToDoName { get; set; }
        public EditToDo EditToDo { get; set; }

        private readonly IToDoApplication _toDoApplication;

        public EditModel(IToDoApplication toDoApplication)
        {
            _toDoApplication = toDoApplication;
        }

        public void OnGet(Guid id)
        {
            Id = id;
            var todo = _toDoApplication.GetTodoById(id);
            EditToDoName = todo.Name;
        }


        public IActionResult OnPostEditToDo(Guid id,string editToDoName)
        {
            _toDoApplication.Edit(new EditToDo { Id = id, Name = editToDoName });
            return RedirectToPage("/ToDoList");
        }
    }
}

SimpleToDolist/Pages/EditAccount.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleToDoList.Application.Contracts.Account;
using System;

namespace SimpleToDoList.Pages
{
    public class EditAccountModel : PageModel
    {
        public Guid Id { get; set; }
        public string FullName { get; set; }
        public string Username { get; set; }
        public string Mobile { get; set; }
        public string NewPassword { get; set; }
        public UpdateAccount updateAccount { get; set; }

        private readonly IAccountApplication _accountApplication;

        public EditAccountModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet()
        {
            Guid loggedInAccountId = GetLoggedInAccountId();
            Id = loggedInAccountId;
            var account = _accountApplication.GetAccountBy(loggedInAccountId);
            FullName = account.Fullname;
            Username = account.Username;
            Mobile = account.Mobile;
            //Password = account.Password;
        }

        private Guid GetLoggedInAccountId()
        {
            if (HttpContext.Session.TryGetValue("AccountId", out var accountIdBytes))
            {
                // Successfully retrieved account ID from session
                return new Guid(accountIdBytes);
            }

            // User not logged in or session doesn't contain the account ID
            return Guid.Empty;
        }

        public IActionResult OnPostUpdateAccount(Guid id, string Fullname, string Username, string Mobile, string newPassword)
        {
            _accountApplication.Edit(new UpdateAccount { Id = id, Fullname = Fullname, Username = Username, Mobile = Mobile,NewPassword= newPassword });
            return RedirectToPage("ToDoList");
        }

    }
}


SimpleToDolist/Pages/EmployeesAssignment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SimpleToDoList.Application.Contracts;
using SimpleToDoList.Application.Contracts.Project;
using SimpleToDoList.Application.Contracts.ProjectTask;

namespace SimpleToDolist.Pages
{
    public class EmployeesAssignmentModel : PageModel
    {
        public IEnumerable<ProjectViewModel> Projects { get; set; }
        public IEnumerable<ProjectTaskViewModel> Tasks { get; set; }
        public IEnumerable<ViewModelToDo> Todos { get; set; }

        private readonly IToDoApplication _todoApplication;
        private readonly IProjectApplication _projectApplication;
        private readonly IProjectTaskApplication _taskApplication;

        public EmployeesAssignmentModel(IToDoApplication todoApplication, IProjectApplication projectApplication, IProjectTaskApplication taskApplication)
        {
            _todoApplication = todoApplication;
            _projectApplication = projectApplication;
            _taskApplication = taskApplication;
        }

        public IActionResult OnGet()
        {
          var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, "username"),
                // Add other claims as needed
            };

            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var principal = new ClaimsPrincipal(identity);

            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);



            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/Index");
            }

            Guid loggedInAccountId = GetLoggedInAccountId();
            Projects = _projectApplication.GetEmployeeProjects(loggedInAccountId);
            Tasks = _taskApplication.GetEmployeeTasks(loggedInAccountId);
            Todos = _todoApplication.GetUserToDos(loggedInAccountId);
            return Page();

        }

        private Guid GetLoggedInAccountId()
        {
            if (HttpContext.Session.TryGetValue("AccountId", out var accountIdBytes))
            {
                // Successfully retrieved account ID from session
                return new Guid(accountIdBytes);
            }

            // User not logged in or session doesn't contain the account ID
            return Guid.Empty;
        }
    }
}

SimpleToDolist/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleToDolist.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SimpleToDolist/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SimpleToDoList.Application;
using SimpleToDoList.Application.Contracts;
using System;
using System.Collections.Generic;
using SimpleToDoList.Application.Contracts.Account;
using Microsoft.AspNetCore.Authentication;

namespace SimpleToDoList.Pages
{
    
    public class IndexModel : PageModel
    {
        public Guid AccountId { get; set; }
        public string FullName { get; set; }
        public string Username { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public int NationalCode { get; set; }

        private readonly IAccountApplication _accountApplication;

        public IndexModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet(Guid id)
        {
            
        }

        public IActionResult OnPostRegister(string fullName, string mobile, string password, string username,int nationalCode)
        {
            _accountApplication.Create(new CreateAccount
                { Fullname = fullName, Mobile = mobile, Password = password, Username = username, NationalCode = nationalCode });
            return Page();
        }


        public IActionResult OnPostLogin(string username, string password)
        {
                var accountId = _accountApplication.Login(new Login { Username = username, Password = password});

            if (accountId != Guid.Empty)
            {
                // Successfully logged in, store the account ID in the session
                HttpContext.Session.Set("AccountId", accountId.ToByteArray());

                // Redirect to ToDoList page with the retrieved account ID
                return RedirectToPage("EmployeesAssignment", new { accountId });
            }
            else
            {
                // Login failed, handle accordingly (show an error message, redirect to login page, etc.)
                return RedirectToPage("Index");
            }
        }
        /* public IActionResult OnPostLogin(string username, string password)
         {
             var accountId = _accountApplication.Login(new Login { Username = username, Password = password });

             if (accountId != Guid.Empty)
             {
                 return RedirectToPage("ToDoList", new { accountId });
             }
             else
             {
                 return RedirectToPage("LoginError");
             }
         }*/
    }
}

SimpleToDolist/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleToDolist.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

SimpleToDolist/Pages/ToDoList.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SimpleToDoList.Application.Contracts;
using System.Collections.Generic;
using System;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using SimpleToDoList.Application.Contracts.Account;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace SimpleToDoList.Pages
{
    public class ToDoListModel : PageModel
    {
        public Guid AccountId { get; set; }
        public string NewToDoName { get; set; }
        public bool Check { get; set; }
        public IEnumerable<ViewModelToDo> ToDos { get; set; }

        //public List<ViewModelToDo> Filter { get; set; }
        public SelectList Filter { get; set; }
        public string SelectedStatus { get; set; }

        private readonly IToDoApplication _toDoApplication;
        private readonly IAccountApplication _accountApplication;

        public ToDoListModel(IToDoApplication toDoApplication, IAccountApplication accountApplication)
        {
            _toDoApplication = toDoApplication;
            _accountApplication = accountApplication;
        }


        public IActionResult OnGet()
        {

            //Guid loggedInAccountId = GetLoggedInAccountId();
            //ToDos = _toDoApplication.GetUserToDos(loggedInAccountId);
            //return Page();


            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, "username"),
                // Add other claims as needed
            };

            var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var principal = new ClaimsPrincipal(identity);

            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);



            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/Index");
            }

            Guid loggedInAccountId = GetLoggedInAccountId();
            ToDos = _toDoApplication.GetUserToDos(loggedInAccountId);
            return Page();

        }



        public IActionResult OnPostCreateToDo(string NewToDoName)
        {
            /*_toDoApplication.Create(new CreateToDo { Name = NewToDoName });
            return RedirectToPage();*/

            Guid loggedInAccountId = GetLoggedInAccountId();

            if (loggedInAccountId == Guid.Empty)
            {
                return RedirectToPage("Index");
            }

            _toDoApplication.Create(new CreateToDo { Name = NewToDoName, AccountId = loggedInAccountId });

            return RedirectToPage();
        }

        private Guid GetLoggedInAccountId()
        {
            if (HttpContext.Session.TryGetValue("AccountId", out var accountIdBytes))
            {
                // Successfully retrieved account ID from session
                return new Guid(accountIdBytes);
            }

            // User not logged in or session doesn't contain the account ID
            return Guid.Empty;
        }



        public IActionResult OnGetUpdateCompletionStatus(Guid id, bool isChecked)
        {
            if (isChecked)
            {
                _toDoApplication.Completed(id);
            }
            else
            {
                _toDoApplication.NotCompleted(id);
            }
            return RedirectToPage("/ToDoList");
        }

        /*public IActionResult OnGetFilterCompletionStatus(bool Check)
        {
            Filter = _toDoApplication.Filter(new FilterStatus { IsComplete = Check });
            return RedirectToPage();
        }
        */

        /*public IActionResult OnGetFilterCompletionStatus(bool Check)
        {
            var filteredToDos = _toDoApplication.Filter(new FilterStatus { IsComplete = Check });

            // Update the Filter property to be a SelectList
            Filter = new SelectList(filteredToDos, "Id", "Name");

            // Set the selected status for the dropdown
            SelectedStatus = Check.ToString();

            // Reload the page
            return RedirectToPage();
        }*/

        /*public IActionResult OnPostFilterCompletionStatus(bool Check)
        {
            Guid loggedInAccountId = GetLoggedInAccountId();
            var filteredToDos = _toDoApplication.Filter(new FilterStatus {AccountId=loggedInAccountId, IsComplete = Check });

            ToDos = filteredToDos;

            return Page();
        }*/
        public IActionResult OnPostLogout()
        {
            _accountApplication.Logout();
            return RedirectToPage("Index");
        }

    }
}

SimpleToDolist/Pages/Edit.cshtml
@page
@model SimpleToDoList.Pages.EditModel
@{
}

<h1>Edit To-Do List</h1>

<form method="post">
    <div>
        <label asp-for="EditToDoName"></label>
        <input asp-for="EditToDoName" />
        <input type="hidden" asp-for="Id" />
        <button type="submit" asp-page-handler="EditToDo">Edit ToDo</button>
    </div>
</form>

SimpleToDolist/Pages/EditAccount.cshtml
@page
@model SimpleToDoList.Pages.EditAccountModel
@{
}

<h1>Edit Account</h1>

<form method="post">
	<div>
		<label asp-for="FullName"></label>
		<input asp-for="FullName"/>
	</div>
	<label asp-for="Username"></label>
	<input asp-for="Username"/>
	<div>
		<label asp-for="Mobile"></label>
		<input asp-for="Mobile"/>
	</div>
	<label asp-for="NewPassword"></label>
	<input asp-for="NewPassword"/>
	<div>
		<input type="hidden" asp-for="Id"/>
		<button type="submit" asp-page-handler="UpdateAccount">Edit Account</button>
	</div>
</form>

SimpleToDolist/Pages/EmployeesAssignment.cshtml
@page
@model SimpleToDolist.Pages.EmployeesAssignmentModel
@{
}

<label>Project </label>
<div id="Grid">
    <table cellpadding="5" cellspacing="0" style="border: 1pxsolid #ccc;font-size: 9pt;font-family:Arial">
        <tr>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">Name</th>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">Status</th>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">CreationDate</th>           
        </tr>
        @foreach (var project in Model.Projects)
        {
            <tr>
                <td style="width:120px;border: 1px solid #ccc">@project.Name</td>

                <td style="width:120px;border: 1px solid #ccc">
                    <input name="IsCompletedToDo" type="checkbox" onchange="updateCompletionStatus('@project.Id', this.checked)" checked="@project.IsActive" />
                </td>

                <td style="width:120px;border: 1px solid #ccc">@project.CreationDate</td>
            </tr>
        }
    </table>
</div>

<label>Task </label>
<div id="Grid">
    <table cellpadding="5" cellspacing="0" style="border: 1pxsolid #ccc;font-size: 9pt;font-family:Arial">
        <tr>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">Name</th>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">Status</th>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">CreationDate</th>
        </tr>
        @foreach (var task in Model.Tasks)
        {
            <tr>
                <td style="width:120px;border: 1px solid #ccc">@task.Name</td>

                <td style="width:120px;border: 1px solid #ccc">
                    <input name="IsCompletedToDo" type="checkbox" onchange="updateCompletionStatus('@task.Id', this.checked)" checked="@task.IsComplete" />
                </td>

                <td style="width:120px;border: 1px solid #ccc">@task.CreationDate</td>
            </tr>
        }
    </table>
</div>
<label>ToDo </label>
<div id="Grid">
    <table cellpadding="5" cellspacing="0" style="border: 1pxsolid #ccc;font-size: 9pt;font-family:Arial">
        <tr>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">Name</th>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">Status</th>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">CreationDate</th>
        </tr>
        @foreach (var toDo in Model.Todos)
        {
            <tr>
                <td style="width:120px;border: 1px solid #ccc">@toDo.Name</td>

                <td style="width:120px;border: 1px solid #ccc">
                    <input name="IsCompletedToDo" type="checkbox" onchange="updateCompletionStatus('@toDo.Id', this.checked)" checked="@toDo.IsComplete" />
                </td>

                <td style="width:120px;border: 1px solid #ccc">@toDo.CreationDate</td>
            </tr>
        }
    </table>
</div>



SimpleToDolist/Pages/Index.cshtml
@page
@model SimpleToDoList.Pages.IndexModel

<div class="row">
	<div class="col-md-6">
		<h2 class="text-left">Register</h2>

		<div class="jumbotron">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <form method="post">
                <div class="form-group">
                    <label asp-for="Username">User Name</label>
                    <input type="text" name="Username" asp-for="Username" class="form-control input-sm" autocomplete="off" placeholder="User Name">
                    <span asp-validation-for="Username" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Mobile">Mobile</label>
                    <input type="text" name="Mobile" autocomplete="off" asp-for="Mobile" class="form-control input-sm" placeholder="Mobile">
                    <span asp-validation-for="Mobile" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FullName">Full Name</label>
                    <input type="text" name="FullName" asp-for="FullName" autocomplete="off" class="form-control input-sm" placeholder="Full Name">
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Password">Password</label>
                    <input type="password" name="Password" asp-for="Password" autocomplete="off" class="form-control input-sm" placeholder="Password">
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NationalCode">National Code</label>
                    <input type="number" name="NationalCode" asp-for="NationalCode" autocomplete="off" class="form-control input-sm" placeholder="National Code">
                    <span asp-validation-for="NationalCode" class="text-danger"></span>
                </div>

                <button type="submit" value="Register" asp-page-handler="Register" class="btn btn-info btn-block">Register</button>
            </form>
		</div>
	</div>

	<div class="col-md-6">
		<h2 class="text-left">Login</h2>

		<div class="jumbotron">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>

			<form method="post">
				<div class="form-group">
					<label asp-for="Username">User Name</label>
					<input type="text" name="Username" asp-for="Username" class="form-control input-sm" autocomplete="off" placeholder="User Name">
					<span asp-validation-for="Username" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="Password">Password</label>
					<input type="password" name="Password" asp-for="Password" autocomplete="off" class="form-control input-sm" placeholder="Password">
					<span asp-validation-for="Password" class="text-danger"></span>
				</div>
				<input type="hidden" asp-for="@Model.AccountId" />
				<button type="submit" value="Login" asp-page-handler="Login" class="btn btn-info btn-block">Login</button>
			</form>
		</div>
	</div>
</div>

SimpleToDolist/Pages/ToDoList.cshtml
@page
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model SimpleToDoList.Pages.ToDoListModel
@{
}

<h1>To-Do List</h1>

<a asp-page="/EditAccount" style="background-color: #FFFF00;" asp-route-id="@Model.AccountId">Edit Account</a>
<form method="post">
    <button type="submit" asp-page-handler="Logout">Logout</button>
</form>

<form method="post">
    <div>
        <label asp-for="NewToDoName"></label>
        <input asp-for="NewToDoName" />
        <button type="submit" asp-page-handler="CreateToDo">Add ToDo</button>

    </div>
</form>
<form method="post">
    <div>
        <!--onchange="this.form.submit()"-->
        <select name="Check" asp-for="SelectedStatus">
            <option value="none">Filter Status</option>
            <option value="True">Completed</option>
            <option value="False">Not Completed</option>
        </select>
        <button type="submit" asp-page-handler="FilterCompletionStatus">Filter</button>
    </div>
</form>


<div id="Grid">
    <table cellpadding="5" cellspacing="0" style="border: 1pxsolid #ccc;font-size: 9pt;font-family:Arial">
        <tr>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">ID</th>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">Name</th>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">Status</th>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">CreationDate</th>
            <th style="background-color: #B8DBFD;border: 1px solid #ccc">Operation</th>
        </tr>
        @foreach (var toDo in Model.ToDos)
        {
            <tr>
                <td style="width:120px;border: 1px solid #ccc">@toDo.Id</td>
                <td style="width:120px;border: 1px solid #ccc">@toDo.Name</td>

                <td style="width:120px;border: 1px solid #ccc">
                    <input name="IsCompletedToDo" type="checkbox" onchange="updateCompletionStatus('@toDo.Id', this.checked)" checked="@toDo.IsComplete" />
                </td>

                <td style="width:120px;border: 1px solid #ccc">@toDo.CreationDate</td>
                <td style="width: 120px; border: 1px solid #ccc">
                    <a asp-page="/Edit" style="background-color: #FFFF00;" asp-route-id="@toDo.Id">Edit</a>

                </td>
            </tr>
        }
    </table>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    function updateCompletionStatus(id, isChecked) {
        $.ajax({
            type: 'GET',
            url: '/ToDoList?handler=UpdateCompletionStatus',
            data: { id: id, isChecked: isChecked },
            success: function () {
                location.reload();
            },
            error: function () {
                alert('Failed to update completion status.');
            }
        });
    }

</script>